### ISSUE TITLE
When flipping pages/tabs rapidly, the app crashes

### ISSUE THREAD

**Issue by haydenwalker980** [Ibrahim778/BetterHomebrewBrowser#9] opened 2021-11-21 20:09 UTC
Console: PS Vita 2000, firmware 3.65 w/Enso
Steps to reproduce: While one page is loading, tap another tab. The app crashes.

**Comment by Ibrahim778** [comment] 2021-11-25 15:47
This is a known bug, been here for a while I know the cause but it's a tricky fix. It *might* be fixed in the next release.

**Closed** 2022-11-07 12:02 UTC
